### ISSUE TITLE
Add ability to delete a users agent when we publish a new version of AD4M launcher

### ISSUE THREAD

**Issue by jdeepee** [coasys/ad4m#165]
In addition to this feature, if we delete a users agent we should display notification modal explaining the migration and that it is expected they will have to create a new account

**Comment by lucksus** [comment]
We can keep the agent keys actually and only reset the rest, as a first and easy step. Second step could be to export and reimport perspective data..

**Comment by jdeepee** [comment]
@lucksus ah yes great point, that would work very well. We should also keep the IPFS data since that already has migration logic, its only holochain that does not have update migration
