### ISSUE TITLE
Launcher's exception pop-up UI is broken

### ISSUE THREAD

**Issue by lucksus** [coasys/ad4m#250]
When the executor tries to install a Language but can't verify the author of the code is trusted, the Launcher flashes (the main window pops up) but it doesn't show any information or UI to add this untrusted author to the list of trusted agents.

Even when navigating to the trusted agents overview, there is no button to add an agent.

This is a regression as both was working/possible before.

**Comment by kaichaosun** [comment]
@leifriksheim  https://github.com/perspect3vism/ad4m/pull/261
