### ISSUE TITLE
Remote ad4m hosting is imported into mono repo

### ISSUE THREAD

**Issue by jdeepee** [coasys/ad4m#291]
(https://github.com/fluxsocial/remote-ad4m)

**Comment by kaichaosun** [comment]
To reiterate my concern, ad4m mono repo in current shape is hard to do `split of concern`. During last a few months, my feeling around the mono repo are,

Pros:
- easy to setup CI steps for multi projects
- easy to send and review the PR

Cons:
- hot reload debug with launcher UI is complex
- cache with turbo is mysterious, sometimes I change the code and build, but I don't get the latest binary package.
- seeing cargo.toml and package.json both lives in root level, rust and js code nested, it feels hard to navigate and reason about.

What's others feelings?

Remote-ad4m repo includes only a few scripts, I think moving it into ad4m mono repo in current shape brings less value and increase burden of above cons.

Dev UX is the key to the success of ad4m ecosystem, I'm wondering if rust devs want to dig into the rabbit hole of javascript, and how javascript devs choose between plain hypercore and ad4m (integrate hypercore into ad4m is not the point we discuss here).
