### ISSUE TITLE
Could not connect to AD4M

### ISSUE THREAD

**Issue by trumanellis** [coasys/ad4m#412]
I just installed the AD4M launcher and created an account. I'm trying to launch the AD4M tutorials but it's not able to connect to the node on my desktop. I only get this error
<img width="1505" alt="Screenshot 2023-10-16 at 11 37 32 AM" src="https://github.com/coasys/ad4m/assets/15612/eac2430b-84fd-4d23-ae41-7217770c5a66">
I get the same error when I try to connect to Flux.
These are my settings in AD4M:
<img width="398" alt="Screenshot 2023-10-16 at 11 40 16 AM" src="https://github.com/coasys/ad4m/assets/15612/5edf4f5b-98eb-4dfa-a40e-3f7a0d19a15b">
<img width="398" alt="Screenshot 2023-10-16 at 11 39 54 AM" src="https://github.com/coasys/ad4m/assets/15612/3d2f656c-c23e-41b4-b19d-79388560546c">

**Comment by jdeepee** [comment]
Hey! Thanks for trying out Adam Layer. This issue might be due to the use of brave with shields enabled which disables communication with localhost. Could you try disabling the brave shields and see if that works?

**Comment by trumanellis** [comment]
Thank you, switching to Chrome worked.
